[context.production]
  publish = "dist/"
  command = "make build"

[[redirects]]
from = "/.well-known/assetlinks.json"
to = "/well-known/assetlinks.json"
status = 200
force = true

[[redirects]]
from = "/.well-known/2023-03-14_linkedin-community-management-api-validation.txt"
to = "/well-known/2023-03-14_linkedin-community-management-api-validation.txt"
status = 200
force = true
